### PR TITLE
Add a API for better module intercompatibility

### PR DESCRIPTION
**Pull request by p4535992**
I added an API to the module to help integration with other modules.

I also added in the API a method to "try" to update the items in an actor with linked ones based on the name for now, it can be extended for more complex cases, but I'll stop there for now.

P.S. I didn't understand if this is a typescript or javascript project.... at a glance it looks like a typescript project to me, can you remove the javascript files that are derived from the compilation ? I think they just create confusion.-

### CODE REVIEW

**Comment by elizeuangelo** [comment]
Sorry for being late on this! I will try getting over it this weekend.

**Comment by p4535992** [comment]
np take your time completely forgot about this XD

**Review by elizeuangelo — APPROVED** [review]

**Comment by elizeuangelo** [comment]
Thank you very much for this API!

I believe I will turn this project into 100% Javascript if I proceed on doing works on it, my initial idea was being 100% typescript but due to foundry-types deprecation it started becoming an issue and difficult to use TS.

**Comment by p4535992** [comment]
Agree. With _FoundryVTT v12_ and the new _ts doc_ there is an integration to generate the typescript, but honestly between vite and svelte using javascript has become less onerous.

**Pull request merged**
